language: python
python:
    - "2.7"
    - "3.5"
    - "3.6"

cache: apt

before_install:
    - "sudo apt-get update"
    - "sudo apt-get install gfortran"

install:
    - "sudo pip install --upgrade pip"
    - "python setup.py build"
    - "python setup.py install"
    
script:
    - py.test

