language: python
python:
    - "2.7"
    - "3.5"
    - "3.6"
    - "3.7"

cache: apt
addons:
  apt:
    packages:
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - gfortran

before_install:
    - "sudo apt-get update"
    - "sudo apt-get install python-numpy"
    - "sudo apt-get install gfortran"
    - "sudo apt-get install python-matplotlib"

install:
    - "python setup.py build"
    - "python setup.py install"
    
script:
    - py.test