language: python
python:
    - "3.6"

before_install:
    - "sudo apt-get update"
    - "sudo apt-get install gfortran"

install:
    - "sudo pip install --upgrade pip"
    - "python setup.py build"
    - "python setup.py install"
    - "ls /home/travis/build/sonofeft/RocketCEA"
    - "ls /home/travis/build/sonofeft/RocketCEA/rocketcea"
    
script:
    - py.test

