language: python
python:
    - "2.7"
    - "3.5"
    - "3.6"

cache: apt
addons:
  apt:
    packages:
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - gfortran

before_install:
    - "sudo apt-get update"
    - "sudo apt-get install gfortran"

install:
    - "sudo pip install numpy"
    - "sudo pip install matplotlib==3.0.3"
    - "python setup.py build"
    - "python setup.py install"
    
script:
    - py.test